# Generated by Django 4.2 on 2024-07-11 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriz',
            name='columnas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='filas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
