# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los requisitos del archivo a la imagen
COPY requirements.txt .

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del proyecto a la imagen
COPY . .

# Exponer el puerto que se va a utilizar
EXPOSE 8000

# Comando por defecto
CMD ["python", "app/manage.py", "runserver", "0.0.0.0:8000"]
